"""baseline schema

Revision ID: b80ab880db99
Revises:
Create Date: 2026-04-12 11:34:25.929369

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b80ab880db99"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("min_players", sa.Integer(), nullable=False),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column("playing_time", sa.Integer(), nullable=False),
        sa.Column("min_playing_time", sa.Integer(), nullable=True),
        sa.Column("max_playing_time", sa.Integer(), nullable=True),
        sa.Column("complexity", sa.Float(), nullable=False),
        sa.Column("thumbnail", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_games_name"), ["name"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings_weighted", sa.Boolean(), nullable=False),
        sa.Column("poll_type", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("hide_voters", sa.Boolean(), nullable=False),
        sa.Column("vote_limit", sa.Integer(), nullable=False),
        sa.Column("shuffle_options", sa.Boolean(), nullable=False),
        sa.Column("hide_results", sa.Boolean(), nullable=False),
        sa.Column("allow_adding_options", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_name", sa.String(), nullable=True),
        sa.Column("telegram_last_name", sa.String(), nullable=True),
        sa.Column("telegram_username", sa.String(), nullable=True),
        sa.Column("bgg_username", sa.String(), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("added_by_user_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("bgg_username"),
    )
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False),
        sa.Column("effective_max_players", sa.Integer(), nullable=True),
        sa.Column("effective_complexity", sa.Float(), nullable=True),
        sa.Column("is_manual_player_override", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "game_id", name="uq_user_game"),
    )
    op.create_table(
        "expansions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_game_id", sa.BigInteger(), nullable=False),
        sa.Column("new_max_players", sa.Integer(), nullable=True),
        sa.Column("complexity_delta", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expansions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expansions_base_game_id"), ["base_game_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expansions_name"), ["name"], unique=False)

    op.create_table(
        "game_night_polls",
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["sessions.chat_id"],
        ),
        sa.PrimaryKeyConstraint("poll_id"),
    )
    op.create_table(
        "session_players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "user_id", name="uq_session_user"),
    )
    op.create_table(
        "poll_added_games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("added_by_user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["game_night_polls.poll_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poll_id", "game_id", name="uq_poll_added_game"),
    )
    with op.batch_alter_table("poll_added_games", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_poll_added_games_poll_id"), ["poll_id"], unique=False)

    op.create_table(
        "poll_votes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("vote_type", sa.String(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=True),
        sa.Column("category_level", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("user_last_name", sa.String(), nullable=True),
        sa.Column("user_tg_username", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["game_night_polls.poll_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "poll_id", "user_id", "vote_type", "game_id", "category_level", name="uq_poll_vote"
        ),
    )
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_poll_votes_poll_id"), ["poll_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_poll_votes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_expansions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expansion_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expansion_id"],
            ["expansions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "expansion_id", name="uq_user_expansion"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_expansions")
    with op.batch_alter_table("poll_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_votes_user_id"))
        batch_op.drop_index(batch_op.f("ix_poll_votes_poll_id"))

    op.drop_table("poll_votes")
    with op.batch_alter_table("poll_added_games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_poll_added_games_poll_id"))

    op.drop_table("poll_added_games")
    op.drop_table("session_players")
    op.drop_table("game_night_polls")
    with op.batch_alter_table("expansions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expansions_name"))
        batch_op.drop_index(batch_op.f("ix_expansions_base_game_id"))

    op.drop_table("expansions")
    op.drop_table("collection")
    op.drop_table("users")
    op.drop_table("sessions")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_name"))

    op.drop_table("games")
    # ### end Alembic commands ###
